swagger: '2.0'
info:
  title: APS MCP Server
  description: MCP Streamable endpoint for Microsoft Copilot Studio integration
  version: 1.0.0
host: aps-mcp-server-1-bnhqa4cce3ese7ew.centralus-01.azurewebsites.net
basePath: /
schemes:
  - https
paths:
  /mcp:
    post:
      summary: Autodesk Platform Services MCP Server
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeMCP
      responses:
        '200':
          description: Success
